/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.IngresosMensuales;

import Presentacion.GestionGastos.Frm_GestionGastos;
import Presentacion.Menu.Presentacion_MenuPrincipal;
import com.mycompany.s_panaderiagestioningresosmensuales.FuncionalidadIngresosMensuales;
import com.mycompany.s_panaderiagestioningresosmensuales.IFuncionalidadIngresosMensuales;

/**
 *
 * @author rramirez
 */
public class FrmIngresosMensuales extends javax.swing.JFrame {

    IFuncionalidadIngresosMensuales funcionalidadIngresosMensuales;

    /**
     * Creates new form FrmIngresosMensuales
     */
    public FrmIngresosMensuales() {
        initComponents();
        funcionalidadIngresosMensuales = new FuncionalidadIngresosMensuales();
        cargarDatos();
    }

    public void cargarDatos() {
        Float ingresos = funcionalidadIngresosMensuales.calcularIngresosTotales();
        LblTotalIngresos.setText("Total:" + String.format("%.2f", ingresos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblGestionGastos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblIngresosM = new javax.swing.JTable();
        BtnRegresar = new javax.swing.JButton();
        BtnVerIngresosMensuales = new javax.swing.JButton();
        LblTotalIngresos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblGestionGastos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblGestionGastos.setForeground(new java.awt.Color(0, 0, 0));
        LblGestionGastos.setText("Ingresos mensuales");
        jPanel1.add(LblGestionGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 6, -1, -1));

        TblIngresosM.setBackground(new java.awt.Color(255, 255, 255));
        TblIngresosM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TblIngresosM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TblIngresosM.setForeground(new java.awt.Color(0, 0, 0));
        TblIngresosM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Año", "Mes", "Numero de ventas", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblIngresosM);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 224));

        BtnRegresar.setBackground(new java.awt.Color(255, 153, 0));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        BtnVerIngresosMensuales.setBackground(new java.awt.Color(255, 153, 0));
        BtnVerIngresosMensuales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnVerIngresosMensuales.setForeground(new java.awt.Color(0, 0, 0));
        BtnVerIngresosMensuales.setText("Ver Gestión Gastos");
        BtnVerIngresosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerIngresosMensualesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVerIngresosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 240, 40));

        LblTotalIngresos.setBackground(new java.awt.Color(0, 0, 0));
        LblTotalIngresos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblTotalIngresos.setForeground(new java.awt.Color(0, 0, 0));
        LblTotalIngresos.setText("Total:");
        jPanel1.add(LblTotalIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        Presentacion_MenuPrincipal m = new Presentacion_MenuPrincipal();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnVerIngresosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerIngresosMensualesActionPerformed
        // TODO add your handling code here:
        Frm_GestionGastos fim = new Frm_GestionGastos();
        fim.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVerIngresosMensualesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIngresosMensuales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton BtnVerIngresosMensuales;
    private javax.swing.JLabel LblGestionGastos;
    private javax.swing.JLabel LblTotalIngresos;
    private javax.swing.JTable TblIngresosM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
