/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.enviarPedidos;

import DTO.DTO_Venta;
import Presentacion.Menu.Presentacion_MenuPrincipal;
import com.mycompany.s_panaderiaenviarpedido.FuncionalidadEnviarPedidos;
import com.mycompany.s_panaderiaenviarpedido.IFuncionalidadEnviarPedido;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NaderCroft
 */
public class DlgEnviarPedidos extends javax.swing.JFrame {

    private IFuncionalidadEnviarPedido enviarPedido;
    /**
     * Creates new form DlgEnviarPedidos
     */
    public DlgEnviarPedidos() {
        initComponents();
        enviarPedido = new FuncionalidadEnviarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fechaInicio = new com.github.lgooddatepicker.components.DatePicker();
        jButton4 = new javax.swing.JButton();
        fechaFin = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        background.setBackground(new java.awt.Color(102, 102, 102));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha", "Total", "Estatus"
            }
        ));
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        jLabel1.setText("Enviar Pedidos");
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        btnRegresarMenu.setText("Regresar Al Menu");
        btnRegresarMenu.setBackground(new java.awt.Color(255, 153, 51));
        btnRegresarMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresarMenu.setToolTipText("");
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        fechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        jButton4.setText("Ir");
        jButton4.setBackground(new java.awt.Color(255, 153, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        fechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegresarMenu)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnRegresarMenu)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (fechaInicio.getDate() == null || fechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "No se selecciono ninguna fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fechaFinal = convertLocalDateToString(fechaFin.getDate());
        if (!esFechaValida(fechaFinal)) {
            JOptionPane.showMessageDialog(this, "No se puede seleccionar una fecha superior a la de hoy", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        llenarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        int respuesta = JOptionPane.showOptionDialog(null, "¿Desea enviar este pedido?", "Envio de pedido", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sí", "No"}, "Sí");
        if (respuesta == JOptionPane.CLOSED_OPTION) {
            return;
        }
        if (respuesta == JOptionPane.YES_OPTION) {
        DTO_Venta venta = new DTO_Venta();
        int fila = tblPedidos.rowAtPoint(evt.getPoint());
        venta.setID(tblPedidos.getValueAt(fila, 0).toString());
        venta = enviarPedido.encontrarVentaPorId(venta.getID());
        Date fechaNueva = new Date();
        venta.setFechaEntrega(fechaNueva);
        enviarPedido.actualizarVenta(venta);
        llenarTabla();
        }else{
        return;
        }
        
        
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        Presentacion_MenuPrincipal menuPrincipal = new Presentacion_MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    
    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblPedidos.getModel();

        modelo.setRowCount(0);

        tblPedidos.setModel(modelo);
    }
    /**
     * Convierte un objeto {@link LocalDate} a una cadena de texto con el
     * formato "yyyy-MM-dd".
     *
     * <p>
     * Este método toma un objeto {@link LocalDate}, lo valida para asegurarse
     * de que no es nulo, y lo convierte en una cadena de texto que representa
     * la fecha en el formato "yyyy-MM-dd".</p>
     *
     * @param date La fecha que se va a convertir a una cadena. No puede ser
     * nula.
     * @return Una cadena de texto que representa la fecha en el formato
     * "yyyy-MM-dd".
     * @throws IllegalArgumentException Si el parámetro {@code date} es nulo.
     */
    private String convertLocalDateToString(LocalDate date) {
        if (date == null) {
            throw new IllegalArgumentException("The date cannot be null.");
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return date.format(formatter);
    }
    private void llenarTabla() {
        limpiarTabla();
        LocalDate fechaInicioLocal = this.fechaInicio.getDate();
        LocalDate fechaFinLocal = this.fechaFin.getDate();
        Date fechaInicio = Date.from(fechaInicioLocal.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        Date fechaFin = Date.from(fechaFinLocal.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        List<DTO_Venta> listaVenta = enviarPedido.consultarVentasPorRangoFechasEntrega(fechaInicio, fechaFin);
        DefaultTableModel modelo = (DefaultTableModel) tblPedidos.getModel();

        if (listaVenta != null) {
            listaVenta.forEach(t -> {
                // Agregar la fila al modelo
                modelo.addRow(new Object[]{t.getID(),t.getCliente().getNombre(),t.getFechaRegistro(), t.getMontoTotal(),t.getEstado()});

            });
        }
    }
    
    /**
     * Valida si una fecha proporcionada como cadena de texto no es posterior a
     * la fecha actual.
     *
     * <p>
     * Este método toma una fecha en formato {@code "yyyy-MM-dd"} (como cadena
     * de texto), intenta convertirla a un objeto {@link Date}, y valida que la
     * fecha no sea posterior al día de hoy.</p>
     *
     * @param fechaStr La fecha en formato {@code "yyyy-MM-dd"} que se va a
     * validar.
     * @return {@code true} si la fecha proporcionada no es posterior a la fecha
     * actual; {@code false} si la fecha es posterior a hoy o si el formato de
     * la fecha es inválido.
     */
    public boolean esFechaValida(String fechaStr) {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        formatoFecha.setLenient(false); // Desactiva la validación leniente

        try {
            // Convertimos la fecha proporcionada (String) a un objeto Date
            Date fechaIngresada = formatoFecha.parse(fechaStr);

            // Obtenemos la fecha actual
            Date fechaHoy = new Date();

            // Comparamos las fechas
            if (fechaIngresada.after(fechaHoy)) {
                return false; // La fecha ingresada es posterior al día de hoy
            }

            return true; // La fecha ingresada es válida (no posterior a hoy)
        } catch (ParseException e) {
            return false; // Si ocurre un error en el formato de la fecha
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnRegresarMenu;
    private com.github.lgooddatepicker.components.DatePicker fechaFin;
    private com.github.lgooddatepicker.components.DatePicker fechaInicio;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
