package Panaderia.IngresosMensuales;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import ConexionBD.ConexionMongoBD;
import Presentacion.GestionGastos.Frm_GestionGastos;
import Presentacion.Menu.Presentacion_MenuPrincipal;
import com.mycompany.s_panaderiagestioningresosmensuales.FuncionalidadIngresosMensuales;
import com.mycompany.s_panaderiagestioningresosmensuales.IFuncionalidadIngresosMensuales;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author rramirez
 */
public class FrmIngresosMensuales extends javax.swing.JFrame {

    IFuncionalidadIngresosMensuales funcionalidadIngresosMensuales;

    ConexionMongoBD co = new ConexionMongoBD("localhost", 27017, "panaderia");

    IFuncionalidadIngresosMensuales funcionalidadIngresosMensuales2 = new FuncionalidadIngresosMensuales(co.getColeccionVentas());
    int anio;
    int mes;

    /**
     * Creates new form FrmIngresosMensuales
     */
    public FrmIngresosMensuales() {
        initComponents();
        funcionalidadIngresosMensuales = new FuncionalidadIngresosMensuales();

        cargarDatos();
    }

    public void cargarDatos() {
        cargarCmbxAnios();
        cargarCmbxMes();
        cargarTabla(2024, 11);
    }

    public void cargarCmbxAnios() {
        try
        {
            List<Integer> anios = funcionalidadIngresosMensuales.obtenerAniosVentas();

            for (Integer anio : anios)
            {
                CmbxAnios.addItem(anio.toString());
            }

        } catch (Exception e)
        {
            System.err.println("Error al cargar los años en el combo box: " + e.getMessage());
            // Manejo de errores según sea necesario
        }
    }

    public void cargarCmbxMes() {
        try
        {
            // Obtén la lista de años de ventas desde la lógica de negocio (BO)
            List<Integer> meses = funcionalidadIngresosMensuales.obtenerMesesVentas();

            // Crea el modelo de combo box y agrega los años a él
            for (Integer mes : meses)
            {
                CmbxMes.addItem(mes.toString());
            }

        } catch (Exception e)
        {
            System.err.println("Error al cargar los años en el combo box: " + e.getMessage());
            // Manejo de errores según sea necesario
        }
    }

    private void cargarTabla(int anio, int mes) {
    // Limpia la tabla para evitar acumulación de datos
    DefaultTableModel modelo = (DefaultTableModel) TblIngresosM.getModel();
    modelo.setRowCount(0); // Limpia las filas de la tabla

    // Consulta los datos para el mes y año seleccionados
    Document listaVentaMes = funcionalidadIngresosMensuales.consultarVentasPorMes(anio, mes);
    System.out.println("Datos obtenidos de la consulta: " + listaVentaMes);

    if (listaVentaMes != null && !listaVentaMes.isEmpty()) {
        // Extrae los valores directamente del Document y maneja el tipo de dato de manera segura
        Integer totalVentas = listaVentaMes.getInteger("totalVentas");
        Object totalMontoObj = listaVentaMes.get("totalMonto"); // Obtiene como Object para determinar el tipo

        if (totalVentas != null && totalMontoObj != null) {
            // Verifica el tipo de totalMonto y convierte a Double si es necesario
            Double totalMonto = null;
            if (totalMontoObj instanceof Double) {
                totalMonto = (Double) totalMontoObj;
            } else if (totalMontoObj instanceof Integer) {
                totalMonto = ((Integer) totalMontoObj).doubleValue();
            }

            if (totalMonto != null) {
                // Agrega los valores a la tabla
                modelo.addRow(new Object[] { totalVentas, totalMonto });
            } else {
                System.err.println("El valor de totalMonto no es un tipo esperado.");
            }
        } else {
            System.err.println("El documento no contiene los datos esperados.");
        }
    } else {
        System.err.println("El documento de ventas es nulo o vacío.");
    }

    TblIngresosM.setModel(modelo);
}


//    private void limpiarTabla() {
//        DefaultTableModel modelo = (DefaultTableModel) TblIngresosM.getModel();
//
//        modelo.setRowCount(0);
//
//        TblIngresosM.setModel(modelo);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblGestionGastos = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        BtnVerIngresosMensuales = new javax.swing.JButton();
        CmbxAnios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CmbxMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblIngresosM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblGestionGastos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblGestionGastos.setForeground(new java.awt.Color(0, 0, 0));
        LblGestionGastos.setText("Ingresos mensuales");
        jPanel1.add(LblGestionGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        BtnRegresar.setBackground(new java.awt.Color(255, 153, 0));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        BtnVerIngresosMensuales.setBackground(new java.awt.Color(255, 153, 0));
        BtnVerIngresosMensuales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnVerIngresosMensuales.setForeground(new java.awt.Color(0, 0, 0));
        BtnVerIngresosMensuales.setText("Ver Gestión Gastos");
        BtnVerIngresosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerIngresosMensualesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVerIngresosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 240, 40));

        CmbxAnios.setBackground(new java.awt.Color(255, 255, 255));
        CmbxAnios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CmbxAnios.setForeground(new java.awt.Color(0, 0, 0));
        CmbxAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbxAniosActionPerformed(evt);
            }
        });
        jPanel1.add(CmbxAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Año");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 30));

        CmbxMes.setBackground(new java.awt.Color(255, 255, 255));
        CmbxMes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CmbxMes.setForeground(new java.awt.Color(0, 0, 0));
        CmbxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbxMesActionPerformed(evt);
            }
        });
        jPanel1.add(CmbxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Mes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 30));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        TblIngresosM.setBackground(new java.awt.Color(255, 255, 255));
        TblIngresosM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TblIngresosM.setForeground(new java.awt.Color(0, 0, 0));
        TblIngresosM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Ventas", "Monto Total"
            }
        ));
        jScrollPane1.setViewportView(TblIngresosM);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 420, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        Presentacion_MenuPrincipal m = new Presentacion_MenuPrincipal();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnVerIngresosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerIngresosMensualesActionPerformed
        // TODO add your handling code here:
        Frm_GestionGastos fim = new Frm_GestionGastos();
        fim.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVerIngresosMensualesActionPerformed

    private void CmbxAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbxAniosActionPerformed
        // TODO add your handling code here:
        if (CmbxAnios.getSelectedItem() != null && CmbxMes.getSelectedItem() != null)
        {
            try
            {
                anio = Integer.parseInt(CmbxAnios.getSelectedItem().toString());
                mes = Integer.parseInt(CmbxMes.getSelectedItem().toString());

                cargarTabla(anio, mes);
            } catch (NumberFormatException ex)
            {
                System.err.println("Error al convertir valores de ComboBox: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_CmbxAniosActionPerformed

    private void CmbxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbxMesActionPerformed
        // TODO add your handling code here:
        if (CmbxAnios.getSelectedItem() != null && CmbxMes.getSelectedItem() != null)
        {
            try
            {
                anio = Integer.parseInt(CmbxAnios.getSelectedItem().toString());
                mes = Integer.parseInt(CmbxMes.getSelectedItem().toString());

                cargarTabla(anio, mes);
            } catch (NumberFormatException ex)
            {
                System.err.println("Error al convertir valores de ComboBox: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_CmbxMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmIngresosMensuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIngresosMensuales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton BtnVerIngresosMensuales;
    private javax.swing.JComboBox<String> CmbxAnios;
    private javax.swing.JComboBox<String> CmbxMes;
    private javax.swing.JLabel LblGestionGastos;
    private javax.swing.JTable TblIngresosM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
